name: CI/CD pipline

on:
  push:
    branches: [ "main" ]

jobs:
  test-app:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare unit tests
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          python -m pytest ./tests/unit

      - name: Run integration tests
        run: |
          python -m pytest ./tests/integration
